# Generated by Django 3.2.4 on 2021-06-26 02:20

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_testuni'),
    ]

    operations = [
    ]
