# Generated by Django 3.2.4 on 2021-06-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_auto_20210626_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='testuni',
            name='uni_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
