# Generated by Django 3.2.4 on 2021-06-26 03:51

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path

DATA_FILENAME = 'test_universities_data.json'
def load_data(apps, schema_editor):
    University = apps.get_model('universities', 'TestUniversity')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects:
            uni_name = obj.get('uni_name','no-name')
            longitude = obj.get('lon', 0)
            latitude = obj.get('lat', 0)
            location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
            University(uni_name=uni_name, location = location).save()

class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_testuni_district'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
